### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by MittchoBaroco** [derFunk/monit-windows-agent#14]
hey,

do you have any example for the configuration file? maybe some comparison with Linux?

**Comment by m4x1202** [comment]
Hey @MittchoBaroco,

there is a template file generated when installing the Agent, which can also be found here: https://github.com/ChimeraEntertainment/monit-windows-agent/blob/master/ChMonitWindowsAgent/Resources/MonitWindowsAgentConfig.xml
This template includes the basic setup, a process and a filesystem.

A comparison to Linux can not easily be done since the configuration formats are just too different (Linux: context-free grammar, Windows: XML).

Hope this helps.
If you have any more questions, i'm happy to help.

**Comment by MittchoBaroco** [comment]
great thanks
